name: main

on: [push]

jobs:
  tests:
    name: Run Test Suite
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-13"]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - run: python -m pip install -e . --user
      - run: coverage run -m pytest
      - run: coverage xml
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
